# Generated by Django 4.2.7 on 2026-06-22 08:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_products_pr_generic_01ff46_idx_products_pr_generic_33f0e6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_supplier_full_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('received_date', models.DateField(db_index=True)),
                ('location', models.CharField(default='Main Store', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('partially_verified', 'Partially Verified'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('delivery_note_number', models.CharField(blank=True, max_length=100)),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_grns', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='inventory.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='inventory.supplier')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_grns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goods Received Note',
                'verbose_name_plural': 'Goods Received Notes',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_accepted', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_rejected', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('rejection_reason', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('good', 'Good Condition'), ('damaged', 'Damaged'), ('defective', 'Defective'), ('expired', 'Expired'), ('wrong_item', 'Wrong Item'), ('short_expiry', 'Short Expiry')], default='good', max_length=20)),
                ('condition_notes', models.TextField(blank=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='Main Store', max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goods_received_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.goodsreceivednote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_items', to='products.product')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_items', to='inventory.purchaseorderitem')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_grn_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
