# Generated by Django 5.2.14 on 2026-06-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_approval_workflow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_approva_a5d649_idx',
            old_name='users_approva_c75ee7_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_approva_72a4b7_idx',
            old_name='users_approva_f80f65_idx',
        ),
    ]
