# Generated by Django 4.2.7 on 2026-06-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_realistic_identity_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_generic_33f0e6_idx',
            old_name='products_pr_generic_01ff46_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_brand_4bfaa4_idx',
            old_name='products_pr_brand_568957_idx',
        ),
    ]
