# Generated by Django 4.2.7 on 2026-06-23 17:09

from django.db import migrations


def seed_units(apps, schema_editor):
    Unit = apps.get_model('products', 'Unit')
    defaults = [
        ('Kilogram', 'kg', 'weight'),
        ('Gram', 'g', 'weight'),
        ('Pound', 'lb', 'weight'),
        ('Ounce', 'oz', 'weight'),
        ('Liter', 'l', 'volume'),
        ('Milliliter', 'ml', 'volume'),
        ('Gallon', 'gal', 'volume'),
        ('Meter', 'm', 'length'),
        ('Centimeter', 'cm', 'length'),
        ('Inch', 'in', 'length'),
        ('Piece', 'pcs', 'count'),
        ('Dozen', 'dz', 'count'),
        ('Box', 'box', 'packaging'),
        ('Carton', 'carton', 'packaging'),
        ('Pack', 'pack', 'packaging'),
    ]
    for name, symbol, unit_type in defaults:
        Unit.objects.get_or_create(name=name, defaults={'symbol': symbol, 'type': unit_type})


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_unit_product_size_product_variant_unit'),
    ]

    operations = [
        migrations.RunPython(seed_units),
    ]
