# Generated by Django 6.0.5 on 2026-05-29 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_approvalrequest_branch_terminal_offlinesynclog'),
        ('products', '0010_productunit_taxcode_product_wholesale_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=160)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('order_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('items', models.PositiveIntegerField(default=1)),
                ('payment_method', models.CharField(default='Credit', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_invoices', to='products.supplier')),
            ],
        ),
    ]
